$(function(){
    $('#all .logo').css({"left":$(document.body).width()/2-275})
    $('#all .play').css({"left":$(document.body).width()/2-170})
    $('#all .a1').css({"left":$(document.body).width()/2-350})
    $('#all .a2').css({"left":$(document.body).width()/2-350})
    $('#all .p1').css({"left":$(document.body).width()/2-350})
    $('#all .p2').css({"left":$(document.body).width()/2-350})
    $('#all .p3').css({"left":$(document.body).width()/2-350})
    $('#all .p4').css({"left":$(document.body).width()/2-350})
    $('#all .ewm_d').css({"left":$(document.body).width()/2-350})
    $('#all .p5').css({"left":$(document.body).width()/2-350})
    $('#all .p6').css({"left":$(document.body).width()/2-350})
    $('#all .p7').css({"left":$(document.body).width()/2-350})
    $('#all .show_img').css({"left":$(document.body).width()/2-350})
    $('#all .bottom').css({"left":$(document.body).width()/2-350})

    $(window).resize(function () {          
        $('#all .logo').css({"left":$(document.body).width()/2-275})
        $('#all .play').css({"left":$(document.body).width()/2-170})
        $('#all .a1').css({"left":$(document.body).width()/2-350})
        $('#all .a2').css({"left":$(document.body).width()/2-350})
        $('#all .p1').css({"left":$(document.body).width()/2-350})
        $('#all .p2').css({"left":$(document.body).width()/2-350})
        $('#all .p3').css({"left":$(document.body).width()/2-350})
        $('#all .p4').css({"left":$(document.body).width()/2-350})
        $('#all .ewm_d').css({"left":$(document.body).width()/2-350})
        $('#all .p5').css({"left":$(document.body).width()/2-350})
        $('#all .p6').css({"left":$(document.body).width()/2-350})
        $('#all .p7').css({"left":$(document.body).width()/2-350})
        $('#all .show_img').css({"left":$(document.body).width()/2-350})
        $('#all .bottom').css({"left":$(document.body).width()/2-350})
    });
    //alert($(document.body).width())
    //alert($(window).width())
    //$("#all").css({"width":$(document.body).width(),"height":($(document.body).width()/700)*4913})
    $("#all .play").click(function(){
        window.open("https://www.bilibili.com/bangumi/play/ss24438/?from=search&seid=8496888360181755275")
    })
})
